#http://localhost:8080/actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

#spring:
# h2:
#console:
#enabled: true
spring:
  datasource:
    url: "jdbc:h2:file:./data/webshopDb"
    #username: ${JDBC_DATABASE_USERNAME}
    #password: ${JDBC_DATABASE_PASSWORD}
    #url: ${JDBC_DATABASE_URL}
    #driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    #database: postgresql
    #database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: true


logging:
  level:
    org:
      springframework:
        security: DEBUG

