#http://localhost:8080/actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  h2:
    console:
      enabled: true

  datasource:
    url: "jdbc:h2:file:./data/webshopDb"
  jpa:
    hibernate:
      ddl-auto: update
      spring:
    open-in-view: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
      enabled: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
